Style.destroy_all
t1 = Style.create :name => 'Ale'
t2 = Style.create :name => 'Lager'
t3 = Style.create :name => 'Pilsner'
t4 = Style.create :name => 'Stout'
t5 = Style.create :name => 'Wheat'
t6 = Style.create :name => 'American-Style Amber/Red Ale'
t7 = Style.create :name => 'American-Style Barley Wine Ale'
t8 = Style.create :name => 'American-Style Brown Ale'
t9 = Style.create :name => 'American-Style Cream Ale'
t10 = Style.create :name => 'American-Style Fruit Beer'
t11 = Style.create :name => 'American-Style Imperial Porter'
t12 = Style.create :name => 'American-Style Imperial Stout'
t13 = Style.create :name => 'American-Style India Pale Ale'
t14 = Style.create :name => 'American-Style Malt Liquor'
t15 = Style.create :name => 'American-Style Pale Ale'
t16 = Style.create :name => 'American-Style Pilsener'
t17 = Style.create :name => 'American-Style Stout'
t18 = Style.create :name => 'American-Style Strong Pale Ale'
t19 = Style.create :name => 'Australian-Style Pale Ale'
t20 = Style.create :name => 'Baltic-Style Porter'
t21 = Style.create :name => 'Belgian-Style Blonde Ale'
t22 = Style.create :name => 'Belgian-Style Flanders Oud Bruin or Oud Red Ale'
t23 = Style.create :name => 'Belgian-Style Flanders Oud Bruin or Oud Red Ale'
t24 = Style.create :name => 'Belgian-Style Fruit Beer'
t25 = Style.create :name => 'Belgian-Style Fruit Lambic'
t26 = Style.create :name => 'Belgian-Style Gueuze Lambic'
t27 = Style.create :name => 'Belgian-Style Lambic'
t28 = Style.create :name => 'Belgian-Style Pale Ale'
t29 = Style.create :name => 'Belgian-Style Witbier'
t30 = Style.create :name => 'Berliner-Style Weisse'
t31 = Style.create :name => 'Bohemian-Style Pilsener'
t32 = Style.create :name => 'Brett Beer'
t33 = Style.create :name => 'British-Style Barley Wine Ale'
t34 = Style.create :name => 'British-Style Imperial Stout'
t35 = Style.create :name => 'Brown Porter'
t36 = Style.create :name => 'California Common Beer'
t37 = Style.create :name => 'Chili Pepper Beer'
t38 = Style.create :name => 'Chocolate or Cocoa Beer'
t39 = Style.create :name => 'Classic English-Style Pale Ale'
t40 = Style.create :name => 'Classic French & Belgian-Style Saison'
t41 = Style.create :name => 'Classic Irish-Style Dry Stout'
t42 = Style.create :name => 'Coffee Beer'
t43 = Style.create :name => 'Contemporary Gose'
t44 = Style.create :name => 'Dortmunder/European-Style Export'
t45 = Style.create :name => 'Double Red Ale'
t46 = Style.create :name => 'English-Style Brown Ale'
t47 = Style.create :name => 'English-Style Dark Mild Ale'
t48 = Style.create :name => 'English-Style India Pale Ale'
t49 = Style.create :name => 'English-Style Pale Mild Ale'
t50 = Style.create :name => 'English-Style Summer Ale'
t51 = Style.create :name => 'European-Style Dark Lager'
t52 = Style.create :name => 'Export-Style Stout'
t53 = Style.create :name => 'Extra Special Bitter'
t54 = Style.create :name => 'Field Beer'
t55 = Style.create :name => 'French-Style Bière de Garde'
t56 = Style.create :name => 'Fruit Wheat Beer'
t57 = Style.create :name => 'German-Style Altbier'
t58 = Style.create :name => 'German-Style Doppelbock'
t59 = Style.create :name => 'German-Style Eisbock'
t60 = Style.create :name => 'German-Style Heller Bock/Maibock'
t61 = Style.create :name => 'German-Style Kölsch'
t62 = Style.create :name => 'German-Style Leichtes Weizen'
t63 = Style.create :name => 'German-Style Maerzen'
t64 = Style.create :name => 'German-Style Oktoberfest/Wiesn'
t65 = Style.create :name => 'German-Style Pilsener'
t66 = Style.create :name => 'German-Style Rye Ale'
t67 = Style.create :name => 'German-Style Schwarzbier'
t68 = Style.create :name => 'Golden or Blonde Ale'
t69 = Style.create :name => 'Golden or Blonde Ale'
t70 = Style.create :name => 'Herb and Spice Beer'
t71 = Style.create :name => 'Imperial or Double India Pale Ale'
t72 = Style.create :name => 'Imperial Red Ale'
t73 = Style.create :name => 'International-Style Pale Ale'
t74 = Style.create :name => 'International-Style Pilsener'
t75 = Style.create :name => 'Irish-Style Red Ale'
t76 = Style.create :name => 'Leipzig-Style Gose'
t77 = Style.create :name => 'Mixed-Culture Brett Beer'
t78 = Style.create :name => 'Münchner (Munich)-Style Helles'
t79 = Style.create :name => 'Münchner Dunkel'
t80 = Style.create :name => 'Oatmeal Stout'
t81 = Style.create :name => 'Old Ale'
t82 = Style.create :name => 'Ordinary Bitter'
t83 = Style.create :name => 'Pumpkin Spice Beer'
t84 = Style.create :name => 'Pumpkin/Squash Beer'
t85 = Style.create :name => 'Robust Porter'
t86 = Style.create :name => 'Rye Beer'
t87 = Style.create :name => 'Scotch Ale'
t88 = Style.create :name => 'Session India Pale Ale'
t89 = Style.create :name => 'Smoke Beer'
t90 = Style.create :name => 'Smoke Porter'
t91 = Style.create :name => 'South German-Style Bernsteinfarbenes Weizen'
t92 = Style.create :name => 'South German-Style Dunkel Weizen'
t93 = Style.create :name => 'South German-Style Hefeweizen'
t94 = Style.create :name => 'South German-Style Kristal Weizen'
t95 = Style.create :name => 'Special or Best Bitter'
t96 = Style.create :name => 'Specialty Honey Beer'
t97 = Style.create :name => 'Specialty Saison'
t98 = Style.create :name => 'Standard Australian Lager'
t99 = Style.create :name => 'Sweet Stout or Cream Stout'
t100 = Style.create :name => 'Traditional German-Style Bock'
t101 = Style.create :name => 'Vienna-Style Lager'
t102 = Style.create :name => 'Wild Beer'
t103 = Style.create :name => 'Wood- and Barrel-Aged Beer'
t104 = Style.create :name => 'Wood- and Barrel-Aged Dark Beer'
t105 = Style.create :name => 'Wood- and Barrel-Aged Pale to Amber Beer'
t106 = Style.create :name => 'Wood- and Barrel-Aged Sour Beer'
t107 = Style.create :name => 'Wood- and Barrel-Aged Strong Beer'
puts "#{ Style.count } styles"
